version: '3.6'

services:
  database:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
    ports:
      - "${DB_PORT:-5432}:5432"
    restart: always
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
#      PGADMIN_DEFAULT_USER: ${PGADMIN_EMAIL:-pgadmin4@pgadmin.org}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    links:
      - database
    restart: always
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - postgres

  web:
    container_name: fastAPI_container
    build: .
    command: uvicorn main:app --host ${HOST_ADD:-0.0.0.0} --port ${HOST_PORT:-8000} --reload
    volumes:
      - .:/app
    ports:
      - "${HOST_PORT:-8000}:8000"
    links:
      - database
    restart: always
    networks:
      - postgres

  tg_bot:
    container_name: bot_container
    build: ./bot
    environment:
      TG_TOKEN: "${TG_TOKEN:-change_me}"
      HOST_PORT: "${HOST_PORT:-8000}"
    ports:
      - "443:443"
    volumes:
      - ./bot:/usr/src/bot
    links:
      - web
    restart: always
    networks:
      - postgres

volumes:
    postgres:
    pgadmin:
    bot:

networks:
  postgres:
    driver: bridge
