"""Initial_commit

Revision ID: a413c8d77b0e
Revises: 
Create Date: 2023-02-05 16:04:56.130375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a413c8d77b0e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timedelta',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('delta', sa.DateTime(), nullable=False),
        sa.Column('created_on', sa.DateTime(), nullable=True),
        sa.Column('updated_on', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id', name='timedelta_id'),
        sa.UniqueConstraint('delta')
    )
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('first_name', sa.String(length=50), nullable=True),
        sa.Column('last_name', sa.String(length=50), nullable=True),
        sa.Column('tg_id', sa.String(length=20), nullable=False),
        sa.Column('timezone', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_on', sa.DateTime(), nullable=True),
        sa.Column('updated_on', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['timezone'], ['timedelta.id'], ),
        sa.PrimaryKeyConstraint('id', name='user_id'),
        sa.UniqueConstraint('tg_id')
    )
    op.create_table('pills',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('pill_name', sa.String(length=50), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_on', sa.DateTime(), nullable=True),
        sa.Column('updated_on', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id', name='pill_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pills')
    op.drop_table('users')
    op.drop_table('timedelta')
    # ### end Alembic commands ###
